# Generated by Django 3.2 on 2022-02-13 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('freindly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sim_free',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_id', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('os', models.CharField(blank=True, max_length=254, null=True)),
                ('screen', models.FloatField(blank=True, null=True)),
                ('camera', models.CharField(blank=True, max_length=254, null=True)),
                ('capacity', models.CharField(blank=True, max_length=254, null=True)),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('storage', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=254, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
        ),
    ]
