# Generated by Django 3.2 on 2022-02-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim_free',
            name='screen',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
