# Generated by Django 3.2 on 2022-02-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220213_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='simfree',
            name='phone_model',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
