# Generated by Django 3.2 on 2022-02-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220214_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='from_cost',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_model',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='rating',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='simfree',
            name='cost',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='simfree',
            name='phone_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='simfree',
            name='phone_model',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='simfree',
            name='storage',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
