# Generated by Django 3.2 on 2022-03-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220219_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='from_cost',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='phone',
            name='color',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='display_store',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='storage',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.DeleteModel(
            name='SimFree',
        ),
    ]
