# Generated by Django 3.2 on 2022-03-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220303_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='color',
            new_name='color_1',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='cost',
            new_name='price',
        ),
        migrations.AddField(
            model_name='phone',
            name='color_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='color_3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='color_4',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
