# Generated by Django 3.2 on 2022-03-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220304_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='price',
            new_name='price_1',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='phone_model',
            new_name='storage_1',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='storage',
            new_name='storage_2',
        ),
        migrations.AddField(
            model_name='phone',
            name='price_2',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='price_3',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='price_4',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='storage_3',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='storage_4',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
