# Generated by Django 3.2 on 2022-03-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220307_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price_1',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price_2',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price_3',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price_4',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='rating',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
