# Generated by Django 3.2 on 2022-03-21 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0014_alter_phone_rating'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('review_title', models.CharField(max_length=64)),
                ('review_body', models.TextField()),
                ('rating', models.IntegerField(blank=True, default=1, null=True)),
                ('phone_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.phone')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Phone Reviews',
                'ordering': ['-date'],
            },
        ),
    ]
