# Generated by Django 3.2 on 2022-03-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_phonereview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonereview',
            name='rating',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
