# Generated by Django 3.2 on 2022-03-24 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_phonereview_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonereview',
            options={'ordering': ['rating'], 'verbose_name_plural': 'Phone Reviews'},
        ),
        migrations.RemoveField(
            model_name='phonereview',
            name='date',
        ),
    ]
