# Generated by Django 3.2 on 2022-03-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220324_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonereview',
            name='phone_name',
            field=models.CharField(max_length=64),
        ),
    ]
